// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package shelter

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Dog struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Breed     string             `json:"breed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
